// ==========================================
// 🚀 1. 遊戲資料庫與模組 (策略模式設計)
// ==========================================

// 招式效果字典 (未來新增招式只要在這裡加一行即可)
const AttackEffects = {
    // 狀態類
    'poison': (attacker, defender, log) => { defender.status.poison = true; log.text += ` ☠️ 中毒！`; },
    'poison_flip': (attacker, defender, log, coinResult) => { if (coinResult) { defender.status.poison = true; log.text += ` ☠️ 中毒！`; } },
    'burn': (attacker, defender, log) => { defender.status.burn = true; log.text += ` 🔥 灼傷！`; },
    'burn_flip': (attacker, defender, log, coinResult) => { if (coinResult) { defender.status.burn = true; log.text += ` 🔥 灼傷！`; } },
    'asleep': (attacker, defender, log) => { defender.status.asleep = true; log.text += ` 💤 睡眠！`; },
    'asleep_flip': (attacker, defender, log, coinResult) => { if (coinResult) { defender.status.asleep = true; log.text += ` 💤 睡眠！`; } },
    'asleep_self': (attacker, defender, log) => { attacker.status.asleep = true; },
    'confuse': (attacker, defender, log) => { defender.status.confused = true; log.text += ` 💫 混亂！`; },
    'confuse_flip': (attacker, defender, log, coinResult) => { if (coinResult) { defender.status.confused = true; log.text += ` 💫 混亂！`; } },
    'confuse_self_flip': (attacker, defender, log, coinResult) => { if (!coinResult) { attacker.status.confused = true; log.text += ` 自己混亂！`; } },
    'paralyze_flip': (attacker, defender, log, coinResult) => { if (coinResult) { defender.status.paralyze = true; log.text += ` ⚡ 麻痺！`; } },
    
    // 增傷與回復類
    'heal_self_20': (attacker, defender, log) => { attacker.currHp = Math.min(attacker.hp, attacker.currHp + 20); },
    'heal_self_30': (attacker, defender, log) => { attacker.currHp = Math.min(attacker.hp, attacker.currHp + 30); },
    'red_hp_burst_40': (attacker, defender, log, coinResult, baseDmg) => { if ((attacker.currHp / attacker.hp) < 0.3) { log.text += ` (💥紅血爆發+40！)`; return baseDmg + 40; } return baseDmg; },
    'red_hp_burst_50': (attacker, defender, log, coinResult, baseDmg) => { if ((attacker.currHp / attacker.hp) < 0.3) { log.text += ` (💥紅血爆發+50！)`; return baseDmg + 50; } return baseDmg; },
    'red_hp_burst_60': (attacker, defender, log, coinResult, baseDmg) => { if ((attacker.currHp / attacker.hp) < 0.3) { log.text += ` (💥紅血爆發+60！)`; return baseDmg + 60; } return baseDmg; },
    'plus_dmg_if_status_30': (attacker, defender, log, coinResult, baseDmg) => { const hasS = attacker.status.poison || attacker.status.burn || attacker.status.asleep || attacker.status.confused || attacker.status.paralyze; if(hasS) { log.text += ` (狀態異常加成+30)`; return baseDmg + 30; } return baseDmg; },
    'plus_dmg_if_status_40': (attacker, defender, log, coinResult, baseDmg) => { const hasS = attacker.status.poison || attacker.status.burn || attacker.status.asleep || attacker.status.confused || attacker.status.paralyze; if(hasS) { log.text += ` (狀態異常加成+40)`; return baseDmg + 40; } return baseDmg; },
    'self_dmg_20': (attacker, defender, log) => { attacker.currHp = Math.max(0, attacker.currHp - 20); showDamage(attacker.uid, 20, 'normal', false, attacker.uid); },
    'self_dmg_30': (attacker, defender, log) => { attacker.currHp = Math.max(0, attacker.currHp - 30); showDamage(attacker.uid, 30, 'normal', false, attacker.uid); },

    // 控制與牽制類
    'cant_act_next': (attacker, defender, log) => { attacker.status.cant_attack = 2; },
    'cant_act_next_and_discard_1': (attacker, defender, log) => { attacker.status.cant_attack = 2; if(attacker.attachedEnergy.length > 0) attacker.attachedEnergy.pop(); log.text += ` (自棄 1 能且下回禁攻)`; },
    'seal_both_discard': (attacker, defender, log) => { defender.status.cant_attack = 1; if(attacker.attachedEnergy.length > 0) attacker.attachedEnergy.pop(); if(defender.attachedEnergy.length > 0) defender.attachedEnergy.pop(); log.text += ` (雙方棄能，敵下回禁攻)`; },
    'immune_next_flip': (attacker, defender, log, coinResult) => { if(coinResult) attacker.status.immune_next = true; },
    'reduce_dmg_taken_30': (attacker, defender, log) => { attacker.status.reduce_dmg_30 = true; },
    'reduce_dmg_taken_50': (attacker, defender, log) => { attacker.status.reduce_dmg_50 = true; },
    'reduce_dmg_taken_flip': (attacker, defender, log, coinResult) => { if(coinResult) attacker.status.reduce_dmg_30 = true; },
    'reduce_dmg_taken_flip_30': (attacker, defender, log, coinResult) => { if(coinResult) { attacker.status.reduce_dmg_30 = true; log.text += ` (下回受傷-30)`; } },
    'enemy_dmg_minus_30': (attacker, defender, log) => { defender.status.enemy_dmg_minus_30 = 2; },
    'calm_mind_20': (attacker, defender, log) => { attacker.buff.dmg = 20; attacker.buff.turns = 2; attacker.status.reduce_dmg_20 = true; },
    'seal_attack': (attacker, defender, log) => { defender.status.cant_attack = 1; if(attacker.attachedEnergy.length > 0) attacker.attachedEnergy.pop(); },
    'discard_1_fire': (attacker, defender, log) => { let r=0; attacker.attachedEnergy = attacker.attachedEnergy.filter(e => { if((e==='fire'||e==='rainbow') && r<1) { r++; return false; } return true; }); },
    'discard_2_fire': (attacker, defender, log) => { let r=0; attacker.attachedEnergy = attacker.attachedEnergy.filter(e => { if((e==='fire'||e==='rainbow') && r<2) { r++; return false; } return true; }); },
    'discard_enemy_energy': (attacker, defender, log) => { if(defender.attachedEnergy.length > 0) defender.attachedEnergy.pop(); },
    'discard_enemy_energy_flip': (attacker, defender, log, coinResult) => { if(coinResult && defender.attachedEnergy.length > 0) defender.attachedEnergy.pop(); },
    'discard_1_elec_and_paralyze': (attacker, defender, log) => { let r=false; attacker.attachedEnergy = attacker.attachedEnergy.filter(e => { if((e==='electric'||e==='rainbow') && !r) { r=true; return false; } return true; }); defender.status.paralyze = true; log.text += ` ⚡ 麻痺！`; }
};

// 寶可夢庫
const POKEMON_DB = [
    { id: 1, name: '妙蛙種子', type: 'grass', hp: 70, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'藤鞭', d:10, cost:['grass'], special:'reduce_dmg_taken_flip_30', desc:'正面下回受傷-30'}, {n:'茂盛鞭打', d:30, cost:['grass','any'], special:'red_hp_burst_40', desc:'HP<30%時傷害+40'}] },
    { id: 2, name: '妙蛙草', type: 'grass', hp: 100, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'寄生種子', d:30, cost:['grass','any'], special:'heal_self_20', desc:'恢復自己20HP'}, {n:'劇毒之鞭', d:50, cost:['grass','grass','any'], special:'poison_flip', desc:'硬幣正面使對手中毒'}] },
    { id: 3, name: '妙蛙花', type: 'grass', hp: 150, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'陽光烈焰', d:70, cost:['grass','grass','any']}, {n:'瘋狂植物', d:130, cost:['grass','grass','grass','any'], special:'cant_act_next_and_discard_1', desc:'下回禁攻且自棄1能'}] },
    { id: 4, name: '小火龍', type: 'fire', hp: 60, weakness: 'water', resistance: {type:'grass', val:20}, attacks: [{n:'抓', d:10, cost:['any'], special:'draw_1', desc:'抽 1 張卡'}, {n:'猛火咆哮', d:30, cost:['fire','any'], special:'red_hp_burst_40', desc:'HP<30%時傷害+40'}] },
    { id: 5, name: '火恐龍', type: 'fire', hp: 90, weakness: 'water', resistance: {type:'grass', val:20}, attacks: [{n:'火焰牙', d:50, cost:['fire','fire']}, {n:'噴射火焰', d:70, cost:['fire','fire','any']}] },
    { id: 6, name: '噴火龍', type: 'fire', hp: 150, weakness: 'water', resistance: {type:'grass', val:20}, attacks: [{n:'空氣斬', d:60, cost:['fire','fire','any']}, { id:'ultimate', n:'大字爆炎', d:140, cost:['fire','fire','fire','any'], special:'discard_2_fire', desc:'喪失2火能量'}] },
    { id: 7, name: '傑尼龜', type: 'water', hp: 70, weakness: 'grass', resistance: {type:'fire', val:20}, attacks: [{n:'縮入殼中', d:10, cost:['water'], special:'immune_next_flip', desc:'正面下回免傷'}, {n:'激流噴射', d:20, cost:['water','any'], special:'red_hp_burst_50', desc:'HP<30%時傷害+50'}] },
    { id: 8, name: '卡咪龜', type: 'water', hp: 90, weakness: 'grass', resistance: {type:'fire', val:20}, attacks: [{n:'水之波動', d:50, cost:['water','water']}, {n:'火箭頭槌', d:70, cost:['water','water','any'], special:'reduce_dmg_taken_flip', desc:'正面受傷-30'}] },
    { id: 9, name: '水箭龜', type: 'water', hp: 150, weakness: 'grass', resistance: {type:'fire', val:20}, attacks: [{n:'堅硬甲殼', d:10, cost:['water','water','any'], special:'reduce_dmg_taken_50', desc:'下回受傷-50'}, {n:'加農水炮', d:130, cost:['water','water','water','any'], special:'dmg_flip', desc:'需擲幣正面成功'}] },
    { id: 25, name: '皮卡丘', type: 'electric', hp: 100, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'高速移動', d:30, cost:['electric'], special:'immune_next_flip', desc:'正面免傷'}, {n:'十萬伏特', d:100, cost:['electric','electric','electric']}] },
    { id: 26, name: '雷丘', type: 'electric', hp: 110, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'電球', d:50, cost:['electric','electric'], special:'paralyze_flip', desc:'硬幣正面麻痺'}, {n:'伏特攻擊', d:120, cost:['electric','electric','electric','any'], special:'self_dmg_20', desc:'自己受到20傷害'}] },
    { id: 133, name: '伊布', type: 'normal', hp: 60, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'咬', d:10, cost:['any'], special:'draw_1', desc:'抽 1 張卡'}, {n:'突擊', d:40, cost:['any','any'], special:'plus_dmg_if_status_30', desc:'異常狀態時傷害+30'}] },
    { id: 134, name: '水伊布', type: 'water', hp: 120, weakness: 'electric', resistance: {type:'fire', val:20}, attacks: [{n:'水槍', d:30, cost:['water','any']}, {n:'泡沫吸取', d:60, cost:['water','water','any'], special:'heal_self_30', desc:'恢復自己30HP'}] },
    { id: 135, name: '雷伊布', type: 'electric', hp: 120, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'二連擊', d:20, cost:['electric','electric'], special:'flip_2_x20', desc:'擲2次硬幣，正面次數x20'}, {n:'十萬伏特', d:90, cost:['electric','electric','any'], special:'discard_1_elec_and_paralyze', desc:'棄1電能，對手必定麻痺'}] },
    { id: 136, name: '火伊布', type: 'fire', hp: 130, weakness: 'water', resistance: {type:'grass', val:20}, attacks: [{n:'破壞火', d:30, cost:['fire','fire'], special:'discard_enemy_energy_flip', desc:'硬幣正面丟棄對手1能量'}, {n:'火焰旋渦', d:100, cost:['fire','fire','any'], special:'self_dmg_20', desc:'自傷20點'}] },
    { id: 196, name: '太陽伊布', type: 'normal', hp: 120, weakness: 'none', resistance: {type:'normal', val:20}, attacks: [{n:'念力', d:40, cost:['any','any'], special:'paralyze_flip', desc:'硬幣正面麻痺'}, {n:'精神強念', d:80, cost:['fire','any','any']}] },
    { id: 197, name: '月亮伊布', type: 'normal', hp: 140, weakness: 'none', resistance: {type:'normal', val:20}, attacks: [{n:'大聲咆哮', d:30, cost:['any','any']}, {n:'月色幻想', d:70, cost:['electric','any','any'], special:'confuse_flip', desc:'硬幣正面對手混亂'}] },
    { id: 470, name: '葉伊布', type: 'grass', hp: 120, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'葉子防守', d:40, cost:['grass','grass'], special:'reduce_dmg_taken_30', desc:'下回合受傷-30'}, {n:'葉刃', d:90, cost:['grass','grass','any']}] },
    { id: 471, name: '冰伊布', type: 'water', hp: 130, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'雪隱', d:30, cost:['water','water'], special:'immune_next_flip', desc:'硬幣正面下回合免傷'}, {n:'冰凍光束', d:100, cost:['water','water','water'], special:'asleep_flip', desc:'硬幣正面對手睡眠'}] },
    { id: 700, name: '仙子伊布', type: 'normal', hp: 130, weakness: 'none', resistance: {type:'normal', val:20}, attacks: [{n:'魅惑之聲', d:40, cost:['any','any'], special:'confuse', desc:'對手必定混亂'}, {n:'月亮之力', d:60, cost:['electric','any','any'], special:'enemy_dmg_minus_30', desc:'下回合對手攻擊力-30'}] },
    { id: 151, name: '夢幻', type: 'normal', hp: 130, weakness: 'none', resistance: {type:'any', val:20}, attacks: [{n:'超感知', d:40, cost:['any','any'], special:'draw_1', desc:'抽 1 張卡'}, {n:'變身', d:10, cost:['fire','electric','any','any'], special:'transform_choose', desc:'複製對手，回後備恢復60HP'}] },
    { id: 143, name: '卡比獸', type: 'normal', hp: 150, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'扣殺抽出', d:30, cost:['any','any'], special:'draw_1', desc:'抽1張卡'}, {n:'泰山壓頂', d:100, cost:['grass','any','any','any'], special:'asleep_self', desc:'使用完自己陷入睡眠'}] },
    { id: 94, name: '耿鬼', type: 'normal', hp: 110, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'毒瓦斯', d:20, cost:['any','any'], special:'poison', desc:'必定中毒'}, {n:'漆黑', d:60, cost:['grass','any','any'], special:'confuse_flip', desc:'硬幣正面對手混亂'}] },
    { id: 38, name: '九尾', type: 'fire', hp: 140, weakness: 'water', resistance: {type:'grass', val:20}, attacks: [{n:'熱風', d:30, cost:['fire','any'], special:'burn_flip', desc:'擲幣正面敵灼傷'}, {n:'灼熱氣息', d:130, cost:['fire','fire','fire','any'], special:'cant_act_next_and_discard_1', desc:'下回禁攻且自棄1能'}] },
    { id: 130, name: '暴鯉龍', type: 'water', hp: 130, weakness: 'electric', resistance: {type:'fire', val:20}, attacks: [{n:'咬碎', d:40, cost:['water','water']}, {n:'破壞光線', d:100, cost:['water','water','any','any'], special:'discard_enemy_energy_flip', desc:'擲幣正面則棄對手1能量'}] },
    { id: 149, name: '快龍', type: 'normal', hp: 150, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'龍爪', d:50, cost:['any','any']}, {n:'流星群', d:70, cost:['water','any','any']}] },
    { id: 448, name: '路卡利歐', type: 'electric', hp: 110, weakness: 'fire', resistance: {type:'normal', val:20}, attacks: [{n:'波導彈', d:30, cost:['electric','any'], special:'damage_flip_20', desc:'硬幣正面傷害+20'}, {n:'起死回生', d:40, cost:['electric','electric','any'], special:'red_hp_burst_60', desc:'HP<30%時傷害+60'}] },
    { id: 815, name: '閃焰王牌', type: 'fire', hp: 140, weakness: 'water', resistance: {type:'grass', val:20}, attacks: [{n:'二連踢', d:50, cost:['fire','any']}, {n:'火焰球', d:120, cost:['fire','fire','any'], special:'discard_2_fire', desc:'使用後喪失2個火能量'}] },
    { id: 812, name: '轟擂金剛猩', type: 'grass', hp: 150, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'鼓打', d:50, cost:['grass','any']}, {n:'木槌', d:130, cost:['grass','grass','grass','any'], special:'self_dmg_30', desc:'自傷 30 HP'}] },
    { id: 282, name: '沙奈朵', type: 'normal', hp: 140, weakness: 'none', resistance: {type:'normal', val:20}, attacks: [{n:'魔法閃耀', d:50, cost:['any','any'], special:'confuse_flip', desc:'正面使敵混亂'}, {n:'封印', d:80, cost:['grass','grass','any','any'], special:'seal_both_discard', desc:'雙方棄能且敵下回禁攻'} ] },
    { id: 865, name: '蔥遊兵', type: 'normal', hp: 110, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'狂舞揮打', d:50, cost:['any','any']}, {n:'流星突擊', d:90, cost:['electric','electric','any'], special:'cant_act_next', desc:'下回合禁攻'} ] },
    { id: 884, name: '鋁鋼龍', type: 'normal', hp: 130, weakness: 'fire', resistance: {type:'grass', val:20}, attacks: [{n:'龍爪', d:50, cost:['any','any']}, {n:'加農光炮', d:110, cost:['electric','any','any','any'], special:'cant_act_next_and_discard_1', desc:'下回禁攻且自棄1能'} ] },
    { id: 810, name: '敲音猴', type: 'grass', hp: 60, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'抓', d:10, cost:['any'], special:'draw_1', desc:'抽 1 張卡'}, {n:'木枝突刺', d:30, cost:['grass','any'], special:'plus_dmg_if_status_40', desc:'異常狀態時傷害+40'} ] },
    { id: 906, name: '新葉喵', type: 'grass', hp: 80, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'飛葉快刀', d:10, cost:['grass'], special:'draw_1', desc:'抽 1 張卡'}, {n:'種子炸彈', d:40, cost:['grass','any'], special:'plus_dmg_if_status_30', desc:'異常狀態時傷害+30'} ] },
    { id: 44, name: '臭臭花', type: 'grass', hp: 80, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'溶解液', d:20, cost:['grass','any'], special:'poison', desc:'必定中毒'}, {n:'誘導香氣', d:10, cost:['grass','any','any'], special:'force_swap_choose', desc:'選擇對手後備與戰鬥互換'}] },
    { id: 869, name: '霜奶仙', type: 'normal', hp: 90, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'裝飾', d:10, cost:['any'], special:'draw_1', desc:'隨機抽卡'}, {n:'魔法閃耀', d:50, cost:['any','any'], special:'confuse_flip', desc:'正面對手混亂'}] },
    { id: 131, name: '拉普拉斯', type: 'water', hp: 120, weakness: 'electric', resistance: {type:'none', val:0}, attacks: [{n:'冰礫', d:20, cost:['water']}, {n:'冰凍光束', d:80, cost:['water','water','any'], special:'asleep_flip', desc:'正面對手睡眠'}] },
    { id: 755, name: '睡睡菇', type: 'grass', hp: 60, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'閃爍', d:10, cost:['grass'], special:'asleep_flip', desc:'正面對手睡眠'}, {n:'吸取', d:20, cost:['grass','any'], special:'heal_self_20', desc:'恢復自己20HP'}] },
    { id: 350, name: '美納斯', type: 'water', hp: 120, weakness: 'electric', resistance: {type:'none', val:0}, attacks: [{n:'水之波動', d:40, cost:['water','any'], special:'asleep_flip', desc:'正面對手睡眠'}, {n:'龍捲風', d:80, cost:['water','water','any'], special:'confuse_flip', desc:'正面對手混亂'}] },
    { id: 883, name: '腮魚海獸', type: 'water', hp: 130, weakness: 'electric', resistance: {type:'none', val:0}, attacks: [{n:'冰凍牙', d:40, cost:['water','water'], special:'paralyze_flip', desc:'正面對手麻痺'}, {n:'凍寒咬', d:90, cost:['water','water','any']}] },
    { id: 12, name: '巴大蝶', type: 'grass', hp: 110, weakness: 'fire', resistance: {type:'none', val:0}, attacks: [{n:'毒粉', d:20, cost:['grass'], special:'poison', desc:'必定中毒'}, {n:'起風', d:50, cost:['any','any']}] },
    { id: 572, name: '奇諾栗鼠', type: 'normal', hp: 90, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'掃尾拍打', d:20, cost:['any','any'], special:'flip_2_x20', desc:'擲2次幣正面次數x20'}, {n:'幫助', d:40, cost:['grass','any','any'], special:'draw_2', desc:'抽 2 張卡'}] },
    { id: 623, name: '泥偶巨人', type: 'normal', hp: 140, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'鐵壁', d:10, cost:['any','any'], special:'reduce_dmg_taken_50', desc:'下回合受傷-50'}, {n:'暗影拳', d:60, cost:['water','any','any'], special:'ignore_resistance', desc:'無視敵方減傷與抗性'}] },
    { id: 877, name: '莫魯貝可', type: 'electric', hp: 110, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'餓肚子', d:10, cost:['any'], special:'draw_1', desc:'抽 1 張卡'}, {n:'氣場輪', d:50, cost:['electric','electric'], special:'paralyze_flip', desc:'正面對手麻痺'}] },
    { id: 828, name: '狐大盜', type: 'normal', hp: 100, weakness: 'none', resistance: {type:'normal', val:20}, attacks: [{n:'偷襲', d:30, cost:['any']}, {n:'大聲咆哮', d:60, cost:['any','any'], special:'enemy_dmg_minus_30', desc:'下回合敵方攻擊-30'}] },
    { id: 461, name: '馬狃拉', type: 'normal', hp: 100, weakness: 'fire', resistance: {type:'none', val:0}, attacks: [{n:'毒爪', d:30, cost:['any'], special:'poison', desc:'必定中毒'}, {n:'暗襲要害', d:70, cost:['any','any']}] },
    { id: 858, name: '布莉姆溫', type: 'normal', hp: 140, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'冥想', d:10, cost:['any'], special:'calm_mind_20', desc:'下回自己傷害+20且受傷-20'}, {n:'精神強念', d:90, cost:['water','water','any'], special:'cant_act_next', desc:'該寶可夢下回合無法使用招式'}] },
    { id: 475, name: '艾路雷朵', type: 'normal', hp: 140, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'劈開', d:50, cost:['any','any']}, {n:'近身戰', d:120, cost:['any','any','any'], special:'self_dmg_20', desc:'自己受到20傷害'}] },
    { id: 701, name: '摔角鷹人', type: 'normal', hp: 80, weakness: 'electric', resistance: {type:'none', val:0}, attacks: [{n:'飛身重壓', d:30, cost:['any']}, {n:'勇鳥猛攻', d:70, cost:['any','any'], special:'self_dmg_20', desc:'自己受到20傷害'}] },
    { id: 835, name: '來電汪', type: 'electric', hp: 70, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'搖尾巴', d:10, cost:['any']}, {n:'臉頰摩擦', d:30, cost:['electric','any'], special:'paralyze_flip', desc:'硬幣正面對手麻痺'}] },
    { id: 820, name: '藏飽栗鼠', type: 'normal', hp: 120, weakness: 'none', resistance: {type:'none', val:0}, attacks: [{n:'咬住', d:30, cost:['any','any']}, {n:'泰山壓頂', d:80, cost:['any','any','any'], special:'paralyze_flip', desc:'正面對手麻痺'}] },
    { id: 907, name: '蒂蕾喵', type: 'grass', hp: 110, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'劈開', d:40, cost:['any','any']}, {n:'毒擊', d:50, cost:['grass','any','any'], special:'poison', desc:'必定中毒'}] },
    { id: 870, name: '列陣兵', type: 'normal', hp: 100, weakness: 'normal', resistance: {type:'none', val:0}, attacks: [{n:'鐵頭', d:30, cost:['any','any'], special:'paralyze_flip', desc:'硬幣正面麻痺'}, {n:'岩石封鎖', d:40, cost:['fire','any','any'], special:'asleep_flip', desc:'硬幣正面睡眠'}] },
    { id: 971, name: '墓仔狗', type: 'normal', hp: 100, weakness: 'normal', resistance: {type:'none', val:0}, attacks: [{n:'挖洞', d:40, cost:['any','any'], special:'immune_next_flip', desc:'正面下回免傷'}, {n:'嬉鬧', d:60, cost:['fire','any','any']}] },
    { id: 912, name: '潤水鴨', type: 'water', hp: 70, weakness: 'electric', resistance: {type:'fire', val:20}, attacks: [{n:'水槍', d:20, cost:['water']}, {n:'液態裂破', d:50, cost:['water','any'], special:'damage_flip_20', desc:'硬幣正面+20傷害'}] },
    { id: 148, name: '哈克龍', type: 'water', hp: 100, weakness: 'electric', resistance: {type:'fire', val:20}, attacks: [{n:'龍之俯衝', d:50, cost:['water','any'], special:'paralyze_flip', desc:'正面麻痺'}, {n:'破壞光線', d:70, cost:['water','any','any'], special:'cant_act_next', desc:'該寶可夢下回合無法使用招式'}] },
    { id: 43, name: '走路草', type: 'grass', hp: 60, weakness: 'fire', resistance: {type:'water', val:20}, attacks: [{n:'催眠粉', d:10, cost:['grass'], special:'asleep', desc:'對手必定睡眠'}, {n:'麻痺粉', d:40, cost:['grass','any'], special:'paralyze_flip', desc:'硬幣正面麻痺'}] },
    { id: 83, name: '大蔥鴨', type: 'normal', hp: 70, weakness: 'electric', resistance: {type:'none', val:0}, attacks: [{n:'突擊', d:20, cost:['any']}, {n:'碎岩', d:30, cost:['any','any'], special:'damage_flip_30', desc:'硬幣正面+30傷害'}] }
];

const TRAINERS_DB=[
    {id:"potion",name:"傷藥",icon:"💊",desc:"回復一隻寶可夢 30 HP",target:"ally"},
    {id:"super_potion",name:"好傷藥",icon:"🍶",desc:"回復一隻寶可夢 50 HP",target:"ally"},
    {id:"full_heal",name:"萬能藥",icon:"🌿",desc:"解除戰鬥寶可夢所有異常狀態",target:"active_ally"},
    {id:"switch",name:"交替",icon:"🔄",desc:"與後備交換(解除異常狀態)",target:"bench"},
    {id:"energy_search",name:"能量搜索",icon:"🔍",desc:"隨機獲得 2 張能量卡",target:"none"},
    {id:"pokemon_catcher",name:"捕捉器",icon:"🥅",desc:"擲硬幣，正面則強制替換對手戰鬥寶可夢",target:"enemy_bench"}, 
    {id:"rescue_stretcher",name:"擔架",icon:"🚑",desc:"從陣亡區復活一隻寶可夢至後備區(恢復半血)",target:"dead_ally"},
    {id:"boss_orders",name:"老大指令",icon:"📢",desc:"無須擲幣，強制將對手一隻後備寶可夢拖至戰鬥區",target:"enemy_bench"},
    {id:"prof_research",name:"博士研究",icon:"🔬",desc:"捨棄現有手牌，重新抽取 3 張卡",target:"none"},
    {id:"muscle_band",name:"力量頭帶",icon:"💪",desc:"我方戰鬥寶可夢攻擊力+20，持續2回合",target:"active_ally"},
    {id:"focus_sash",name:"氣勢披帶",icon:"🎗",desc:"滿血時若受致命傷，保留10HP不氣絕(觸發後棄置)",target:"active_ally"},
    {id:"full_face_guard",name:"全罩防守",icon:"🛡️",desc:"受傷-20(持續3回合)",target:"ally"},
    {id:"pot_helmet",name:"鍋型頭盔",icon:"🪖",desc:"受傷-40(限最大HP<100，持續2回合)",target:"ally"}
];